
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

output "agent-frontend_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.agent-frontend.service_uri
}
output "agent-backend_service_uri" {
  description = "The main URI in which this Service is serving traffic."
  value       = module.agent-backend.service_uri
}
