
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  billing_project       = "avid-day-459521-r4"
  user_project_override = true
}
provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  billing_project       = "avid-day-459521-r4"
  user_project_override = true
}
