
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

variable "agent-frontend_project_id" {
  description = "The project ID to deploy to"
  type = string
}
variable "agent-frontend_location" {
  description = "Cloud Run service deployment location"
  type = string
}
variable "agent-frontend_service_name" {
  description = "The name of the Cloud Run service to create"
  type = string
}
variable "apphub_project_id" {
  description = "The project ID of the host project where AppHub application is created."
  type = string
}
variable "apphub_location" {
  description = "The location of AppHub application."
  type = string
}
variable "apphub_application_id" {
  description = "The AppHub application identifier"
  type = string
}
